version: '3'
services:
  app:
    container_name: cardgame-app
    image: cardgame-app:v1
    build: .
    links:
      - redis
    ports:
      - "8080:8080"
  redis:
    container_name: redis
    image: redis:v1
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"