version: '3'
services:
  app:
    container_name: spring_boot_main_app
    image: cardgame-app:latest
    build: .
    links:
      - redis
    ports:
      - "8080:8080"
  redis:
    container_name: redis_db
    image: redis:latest
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"