name: Master - Testing

on:
  push:
    branches:
      - 'master'

jobs:

  artifact:

    name: Test master branch - GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'oracle'
          architecture: x64
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: target/cardgame-0.0.1-SNAPSHOT.jar
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: my-artifact
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: cardgame-app:latest
          build-args: JAR_FILE=my-artifact/cardgame-0.0.1-SNAPSHOT.jar
