name: Master - Testing

on:
  push:
    branches:
      - 'master'

jobs:

  artifact:

    name: Test master branch - GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'oracle'
          architecture: x64
      - name: Set executable permissions
        run: chmod +x webpack_task.bat
      - name: Run Webpack Task
        run: ./webpack_task.bat
      - name: Maven Package
        run: mvn -B clean package -DskipTests
